# pre-commit, once installed, runs these specified tools to format/lint/check our code for a consistent standard.
# see https://pre-commit.com/ for more
repos:
# isort re-formats import orders to a standard, see https://pycqa.github.io/isort/index.html for more
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      name: isort (python)
# black re-formats code to an opinionated standard, see https://black.readthedocs.io/en/stable/index.html for more
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.10
# flake8 checks code to make sure it conforms to pep8 (we specify things to ignore in tox.ini)
# see https://flake8.pycqa.org/en/latest/ for more
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
# this custom hook suppresses Jupyter Notebook outputs to keep sensitive data about our partners from leaking
# (see: https://zhauniarovich.com/post/2020/2020-06-clearing-jupyter-output/)
-   repo: local
    hooks:
    - id: nb-clear-output
      name: nb-clear-output
      files: \.ipynb$
      stages: [commit]
      language: system
      entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
# black, flake8 and isort for Jupyter notebooks
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.1
    hooks:
    - id: nbqa-black
      additional_dependencies: [black==22.3.0]
      args: [--nbqa-mutate]
    - id: nbqa-flake8
      additional_dependencies: [flake8==3.7.9]
      args: [--nbqa-mutate]
    - id: nbqa-isort
      additional_dependencies: [isort==5.10.1]
      args: [--nbqa-mutate]