# TODO: Regex tests
#
# COMPONENT 1970-01-01:
#
# - eng_section: Must pass all (or a representative sample) of these:
# /dallas-forgot/
# /dallas-news/
# /food-apartheid/
# /south-dallas/
# /west-dallas/
# /uncategorized/
# /tag/community-meeting/
# /tag/2020-21/
# /tag/2021/
# /tag/7-eleven/
# /tag/75212/
# /tag/accessibile-transportation/
# /tag/accessibility/
# /tag/accountability/
# /tag/ace-cash-express/
# /tag/act/
# /tag/activities/
# /tag/adam-bazaldua/
# /tag/addy-foundation/
# /tag/advocates-for-community-transformation/
# /tag/african-american-museum/
# /tag/african-american/
# /tag/after-school/
# /tag/air-pollution/
# /tag/al-dia/
# /tag/al-lipscomb/
# /tag/alendra-lyons/
# /tag/alexander-esposito/
# /tag/amazon/
# /tag/amazon-fresh/
# /tag/anga-sanders/
# /tag/anita-martinez/
# /tag/anna-hill/
# /tag/appraisal/
# /tag/area-plan/
# /tag/art/
# /tag/artists/
# /tag/aunt-bettes/
# /tag/authors/
# /tag/back-to-school/
# /tag/barriers/
# /tag/basketball/
# /tag/baylor-scott-white-health-and-wellness-center/
# /tag/baylor-university/
# /tag/bc-workshop/
# /tag/benito-juarez/
# /tag/bernal-drive/
# /tag/big-tex-urban-farms-2/
# /tag/black/
# /tag/black-businesses/
# /tag/black-community/
# /tag/black-lives-matter/
# /tag/black-panther-party/
# /tag/black-women/
# /tag/black-womens-united-front/
# /tag/block/
# /tag/bobbie-blair/
# /tag/bond-package/
# /tag/bonton/
# /tag/bookman/
# /tag/books/
# /tag/boxers/
# /tag/boxing/
# /tag/boxing-match/
# /tag/bridge-builders/
# /tag/broadcasts/
# /tag/brother-bills/
# /tag/brown/
# /tag/bruce-carter/
# /tag/builders-of-hope/
# /tag/bus/
# /tag/bus-route/
# /tag/bushman-elementary-school/
# /tag/business-model/
# /tag/camp/
# /tag/cara-mendelsohn/
# /tag/cardboard-project/
# /tag/carpenters-point/
# /tag/cassandra-laster/
# /tag/cedar-valley-campus/
# /tag/cellular-tower/
# /tag/center-for-media-engagement/
# /tag/characters/
# /tag/charolotte-journalism-collaborative/
# /tag/child-poverty-action-lab/
# /tag/childcaregroup/
# /tag/chip/
# /tag/chromebook-bundle/
# /tag/church/
# /tag/circuit/
# /tag/city-bureau/
# /tag/city-council/
# /tag/city-of-dallas/
# /tag/city-plan-commission/
# /tag/citysquare/
# /tag/civic-engagement/
# /tag/civic-producer/
# /tag/clean-air-act/
# /tag/client-choice/
# /tag/collaborative/
# /tag/colloqate-design/
# /tag/commissioner-wheeler/
# /tag/communities-foundation-of-texas/
# /tag/community/
# /tag/community-benefit/
# /tag/community-garden/
# /tag/community-investment/
# /tag/community-journalism/
# /tag/community-stories/
# /tag/community-powered/
# /tag/computer/
# /tag/connection/
# /tag/connectivity/
# /tag/construction/
# /tag/contactless/
# /tag/coordinator/
# /tag/cornerstone-baptist-church/
# /tag/covid/
# /tag/covid-19/
# /tag/cpc/
# /tag/critical-thinking/
# /tag/crossroads-community-services/
# /tag/curb-to-curb/
# /tag/curbside/
# /tag/d-magazine/
# /tag/dallas/
# /tag/dallas-area-rapid-transit-police/
# /tag/dallas-bethlehem-center/
# /tag/dallas-catalyst-project/
# /tag/dallas-college/
# /tag/dallas-documenters/
# /tag/dallas-doing-good/
# /tag/dallas-farmers-market/
# /tag/dallas-fire-rescue/
# /tag/dallas-free-press/
# /tag/dallas-isd/
# /tag/dallas-media-collaborative/
# /tag/dallas-museum-of-art/
# /tag/dallas-museum-of-natural-history-science/
# /tag/dallas-park-and-recreation/
# /tag/dallas-public-library/
# /tag/dallas-weekly/
# /tag/dallas-west-branch-library/
# /tag/damage-assessment/
# /tag/darkwood-gallery/
# /tag/dart/
# /tag/dawson-state-jail/
# /tag/dcad/
# /tag/dell-laptop-bundle/
# /tag/despensas-de-comida/
# /tag/development/
# /tag/dfw/
# /tag/diane-ragsdale/
# /tag/digital-divide/
# /tag/disaster-assitance/
# /tag/disd/
# /tag/district-7/
# /tag/district-7-cpc/
# /tag/district-six/
# /tag/diversity/
# /tag/do-right-by-the-streets-2/
# /tag/documenters/
# /tag/doggie-daycare/
# /tag/doggy-daycare/
# /tag/dolphin-heights/
# /tag/donald-wesson-jr/
# /tag/downwinders-at-risk/
# /tag/dr-carolee-estelle/
# /tag/dr-fred-jones/
# /tag/drbts/
# /tag/driskell/
# /tag/drive/
# /tag/ebt/
# /tag/education/
# /tag/elizabeth-wattley/
# /tag/emergency-connectivity-fund/
# /tag/empowering-the-masses/
# /tag/empowerment-pop-ups/
# /tag/environment/
# /tag/environmental-commission/
# /tag/environmental-justice/
# /tag/epa/
# /tag/equity/
# /tag/esther-villarreal/
# /tag/evo-sadowsky/
# /tag/fair-park/
# /tag/fair-park-dallas/
# /tag/fair-park-first/
# /tag/fairview-youth-foundation/
# /tag/families/
# /tag/federal-permit/
# /tag/feed-oak-cliff/
# /tag/felicia-pierson/
# /tag/fence/
# /tag/field/
# /tag/fiesta/
# /tag/fixed-route/
# /tag/food-access/
# /tag/food-apartheid/
# /tag/food-desert/
# /tag/food-distribution/
# /tag/food-pantry/
# /tag/food-park/
# /tag/food-stamps/
# /tag/forest-forward/
# /tag/forest-theater/
# /tag/formerly-incarcerated/
# /tag/forward-dallas/
# /tag/frazier-revitaliztion/
# /tag/free/
# /tag/froswa-booker-drew/
# /tag/fundraising/
# /tag/gaf/
# /tag/garden/
# /tag/gardener/
# /tag/gathering-place/
# /tag/gentrification/
# /tag/golink/
# /tag/golink-rides/
# /tag/golink-tap-card/
# /tag/grand-place/
# /tag/grants/
# /tag/groceries/
# /tag/grocery-delivery/
# /tag/grocery-store/
# /tag/grocery-stores/
# /tag/gun-violence/
# /tag/gym/
# /tag/h-e-b/
# /tag/harold-simmons-park/
# /tag/hatties-rankin-moore-park/
# /tag/healthy-food/
# /tag/healthy-neighborhood/
# /tag/hesitancy/
# /tag/high-school/
# /tag/hipp/
# /tag/hiring/
# /tag/history/
# /tag/home-improvement/
# /tag/home-improvement-grant/
# /tag/home-repair/
# /tag/home-repair-grant/
# /tag/home-repairs/
# /tag/hot-meals/
# /tag/hot-spot/
# /tag/hotspot/
# /tag/hotspots/
# /tag/housing-and-homeless-solutions-committee/
# /tag/housing-and-neighborhood-revitalization/
# /tag/housing-quality/
# /tag/icdc/
# /tag/ice-cream/
# /tag/incarcerated-artists/
# /tag/innovation/
# /tag/internet-access/
# /tag/internet-service/
# /tag/isolation/
# /tag/jakwan-riddick/
# /tag/james-armstrong-iii/
# /tag/james-madison-high-school/
# /tag/james-mirras/
# /tag/jaycee-zaragoza/
# /tag/jesse-landry/
# /tag/jimesa-duckworth/
# /tag/jimmy-dorrell/
# /tag/jll-research/
# /tag/job/
# /tag/joppa/
# /tag/journalism/
# /tag/journalism-pathway/
# /tag/jubilee-market/
# /tag/jubilee-park-community-center/
# /tag/kathlyn-joy-gilliam-museum/
# /tag/katrina-scott/
# /tag/kera/
# /tag/kim-leeson/
# /tag/kroger/
# /tag/krr-construction/
# /tag/ku-klux-klan/
# /tag/l-g-pinkston-high-school/
# /tag/la-bajada/
# /tag/lady-vikings/
# /tag/land-use/
# /tag/landmark/
# /tag/larry-james/
# /tag/last-mile/
# /tag/latino/
# /tag/latinx/
# /tag/learning-loss/
# /tag/ledbetter-2/
# /tag/ledbetter-neighborhood-association/
# /tag/legal-aid-of-northwest-texas/
# /tag/levees/
# /tag/library/
# /tag/lincoln-high-school/
# /tag/lit-lab/
# /tag/literacy/
# /tag/local/
# /tag/local-business/
# /tag/local-government/
# /tag/local-media/
# /tag/locked/
# /tag/lorenzo-de-zavala-elementary-school/
# /tag/los-altos/
# /tag/los-gallos/
# /tag/malcolm-x-plaza/
# /tag/malcom-x-boulevard/
# /tag/manager/
# /tag/margaret-hunt-hill-bridge/
# /tag/marquee/
# /tag/martin-luther-king-branch-library/
# /tag/martin-luther-king-jr-boulevard/
# /tag/martin-luther-king-jr-boulevards/
# /tag/masterplan/
# /tag/media/
# /tag/media-coverage/
# /tag/media-literacy/
# /tag/mental-health/
# /tag/mercy-street/
# /tag/metro-transit/
# /tag/metropolitan-dream-center/
# /tag/mighty-vikings/
# /tag/miles-of-freedom/
# /tag/mill-city/
# /tag/mlk/
# /tag/mlk-branch-library/
# /tag/mlk-food-park/
# /tag/mobile-hotspot/
# /tag/moni-gee/
# /tag/mr-imagination/
# /tag/my-grocery-store-network/
# /tag/naacp/
# /tag/naacp-youth-council/
# /tag/neighborhood/
# /tag/neighborhood-empowerment-zone/
# /tag/neighborhood-plan/
# /tag/neighborhood-self-defense-project/
# /tag/network/
# /tag/new-years/
# /tag/new-years-day/
# /tag/news/
# /tag/news-and-information/
# /tag/news-consumption/
# /tag/newsrooms/
# /tag/nez-program/
# /tag/nicole-smith/
# /tag/nicolle-stovall/
# /tag/nietta-reynolds/
# /tag/nitashia-johnson/
# /tag/nonprofit/
# /tag/north-texas-food-bank/
# /tag/not-my-son/
# /tag/noticias-de-dallas-2/
# /tag/oak-cliff-veggie-project/
# /tag/office-of-economic-development/
# /tag/omar-narvaez/
# /tag/on-call/
# /tag/online-school/
# /tag/open-government/
# /tag/operation-connectivity/
# /tag/orlando-riddick/
# /tag/overlook/
# /tag/paid-volunteers/
# /tag/pandemic/
# /tag/parade/
# /tag/paratransit/
# /tag/park/
# /tag/park-south-ymca/
# /tag/parkland-hospital/
# /tag/parque-de-heroes/
# /tag/pastor-chris-simmons/
# /tag/pathway/
# /tag/paul-l-dunbar/
# /tag/paul-quinn-college/
# /tag/pd/
# /tag/pd-595/
# /tag/pearl-c-anderson/
# /tag/pearl-c-anderson-learning-center/
# /tag/pearl-c-anderson-middle-school/
# /tag/perot-museum-of-nature-science/
# /tag/philanthropy/
# /tag/phyllis-wheatley-school/
# /tag/pid/
# /tag/pinkston-2/
# /tag/pinkston-high-school/
# /tag/plan-commissioner/
# /tag/planning/
# /tag/planning-and-urban-design/
# /tag/planning-district/
# /tag/plaza/
# /tag/plumbing/
# /tag/podcast/
# /tag/police-brutality/
# /tag/policy/
# /tag/pollock-gallery/
# /tag/pollution/
# /tag/position/
# /tag/power-outage/
# /tag/presidential-election/
# /tag/produce-boxes/
# /tag/program-eligibility/
# /tag/progressive-baptist-church/
# /tag/project-manager/
# /tag/projects/
# /tag/property-taxes/
# /tag/property-values/
# /tag/protest/
# /tag/protests/
# /tag/public-benefit/
# /tag/public-hearing/
# /tag/public-improvement-district/
# /tag/public-meetings/
# /tag/public-safety/
# /tag/purpleair/
# /tag/racism/
# /tag/rail/
# /tag/rail-station/
# /tag/recreation-center/
# /tag/resolve-philly/
# /tag/resources/
# /tag/restorative-farms/
# /tag/revenue/
# /tag/revitalize-south-dallas-coalition/
# /tag/rezoning/
# /tag/ride-share/
# /tag/roofing/
# /tag/rsdc/
# /tag/safe-communities/
# /tag/salaries/
# /tag/save-a-lot/
# /tag/school/
# /tag/schools/
# /tag/shannon-trejo/
# /tag/sharks/
# /tag/sherman/
# /tag/sherri-mixon/
# /tag/shingle-plant/
# /tag/shockley-family-foundation/
# /tag/singleton/
# /tag/singleton-united-unidos/
# /tag/smu/
# /tag/smu-budd-center/
# /tag/smu-simmons-school-of-education/
# /tag/snap/
# /tag/soccer/
# /tag/socialwyze/
# /tag/solutions-journalism/
# /tag/south-dallas/
# /tag/south-dallas-fair-park/
# /tag/south-dallas-fair-park-area-plan/
# /tag/south-irving/
# /tag/south-oak-cliff/
# /tag/southeast-garland/
# /tag/souther-christian-leadership-conference/
# /tag/southern-dallas/
# /tag/southern-dallas-progress/
# /tag/southern-methodist-university/
# /tag/southern-skates-roller-rink/
# /tag/southpoint-community-market/
# /tag/specific-use-permit/
# /tag/spectrum/
# /tag/speed-bumps/
# /tag/ssdfp/
# /tag/st-philips/
# /tag/state-fair/
# /tag/state-fair-of-texas/
# /tag/stem/
# /tag/storytelling/
# /tag/street-racing/
# /tag/student-journalists/
# /tag/student-newsroom/
# /tag/students/
# /tag/sulfur-dioxide/
# /tag/summer/
# /tag/sunny-south-dallas/
# /tag/sunny-south-dallas-food-park/
# /tag/sup/
# /tag/survey/
# /tag/sweet-georgia-brown-bar-b-que/
# /tag/swim-team/
# /tag/swimming/
# /tag/tamia-flores/
# /tag/tap-for-half/
# /tag/target/
# /tag/targeted-rehab-program/
# /tag/tax-abatement/
# /tag/tax-freeze/
# /tag/tax-increase/
# /tag/tceq/
# /tag/teacher/
# /tag/teaching/
# /tag/technology-at-home-program/
# /tag/temporary-housing/
# /tag/tennel-atkins/
# /tag/texas/
# /tag/texas-education-agency/
# /tag/texas-instruments/
# /tag/texas-metro-news/
# /tag/texas-rangers/
# /tag/texas-rangers-youth-academy/
# /tag/texas-state-fair/
# /tag/the-cities-ofrefuge-church/
# /tag/the-dallas-gateway/
# /tag/the-dallas-morning-news/
# /tag/the-help-show/
# /tag/the-real-estate-council/
# /tag/the-toler-co/
# /tag/thomas-edison-middle-school/
# /tag/timeline/
# /tag/timothy-jackson/
# /tag/tony-moore/
# /tag/tournament/
# /tag/tower/
# /tag/toyota/
# /tag/toyota-mobility-foundation/
# /tag/tr-hoover-cdc/
# /tag/tr-hover-learning-garden/
# /tag/tracy-lindsey/
# /tag/traffic-solutions/
# /tag/tramonica-brown/
# /tag/transit/
# /tag/transparency/
# /tag/transportaion/
# /tag/transportation/
# /tag/travel/
# /tag/trec/
# /tag/trinity-groves/
# /tag/trinity-park-conservancy/
# /tag/trinity-river/
# /tag/trp/
# /tag/uberpool/
# /tag/unemployed/
# /tag/university-of-north-texas/
# /tag/university-of-north-texas-at-dallas/
# /tag/untd-school-of-business/
# /tag/untd-serch-institute/
# /tag/urban-farm/
# /tag/urban-planning/
# /tag/urban-policy/
# /tag/urban-redevelopment/
# /tag/urban-renewal/
# /tag/urban-research-initiative/
# /tag/usda/
# /tag/ut-austin/
# /tag/va-medical-center/
# /tag/victory-gardens/
# /tag/violas-house/
# /tag/violent-crime-task-force/
# /tag/virtual-learning/
# /tag/virtual-school/
# /tag/vogel-alcove/
# /tag/voice-of-hope/
# /tag/voice-of-hope-ministries/
# /tag/w-w-caruth-fund/
# /tag/waco/
# /tag/walmart/
# /tag/watchmen/
# /tag/water-pipes/
# /tag/watermark-community-church/
# /tag/watermark-community-church-south-dallas/
# /tag/watermark-community-development-corporation/
# /tag/watermark-health-mobile-clinic/
# /tag/watermark-south-dallas/
# /tag/watermark-south-dallas-campus/
# /tag/wbap-tv/
# /tag/wd/
# /tag/weatherization-assistance-program/
# /tag/weiss-manfredi/
# /tag/wendelkin/
# /tag/wesley-rankin-community-center-2/
# /tag/wesley-rankin-community-center/
# /tag/west-dallas/
# /tag/west-dallas-1/
# /tag/west-dallas-community/
# /tag/west-dallas-multipurpose-center/
# /tag/west-dallas-targeted-rehab-program/
# /tag/west-dallas-trp/
# /tag/wheatley-place/
# /tag/wic/
# /tag/wifi/
# /tag/winter-storm/
# /tag/wired-internet/
# /tag/wireless-internet/
# /tag/wireless-network/
# /tag/writing/
# /tag/yasmine-crockett/
# /tag/youth-academy/
# /tag/zoning/
# /tag/zoning-change/
# /tag/zoning-districts/
# /tag/zoning-process/
#
# spa_section: Following ones & all eng_section tags prepended by "/es"
# /es/dallas-forgot/
# /es/noticias-de-dallas/
# /es/food-apartheid-es/
# /es/south-dallas/
# /es/sin-categorizar/
# /es/west-dallas/
